/**
 * Mağaza metinleri — 23 dil.
 *
 * Sınırlar (`aso.mjs` doğrular):
 *   title ≤ 30 · subtitle ≤ 30 (iOS alt başlık) · short ≤ 80 (Play kısa açıklama)
 *   keywords ≤ 100 (iOS, virgülle, boşluksuz) · promo ≤ 170 (iOS tanıtım metni)
 *   screens: 6 ekran görüntüsü metni, her biri ≤ 40 karakter
 *   description = intro + features + safety + closing (≤ 4000)
 *
 * Metinler çeviri değil, o dilde yazılmıştır: anahtar kelime o pazarın aradığı sözcüktür
 * (DE "Wandern", RU "поход", NE "पदयात्रा"). Marka adı **Zirtan** hiçbir dilde çevrilmez.
 */

export const STORE_COPY = {
  tr: {
    title: 'Zirtan: Doğa, Kamp, Rota',
    subtitle: 'Rota, tehlike haritası, SOS',
    short: 'Yürüyüş arkadaşı bul, tehlike haritasına bak, çevrimdışı harita ve SOS ile çık.',
    keywords: 'kamp,trekking,dağcılık,tırmanış,rota,gps,yürüyüş,doğa,sos,ilk yardım,kaçkar,likya',
    promo: 'Yeni: 12 çevrimdışı ilk yardım rehberi ve ülkeye göre acil numara. Kâşif planı ücretsiz.',
    screens: [
      'Yakındaki maceraperestlerle eşleş',
      'Patikadaki tehlikeyi önceden gör',
      'Basılı tut: SOS ve konum',
      'Şebeke yokken ilk yardım',
      'Çevrimdışı harita ve GPX',
      'Kulübünün etkinlikleri tek yerde',
    ],
    intro:
      'Zirtan, doğaya birlikte ve daha hazırlıklı çıkman için yapıldı. Yakınındaki doğrulanmış maceraperestlerle eşleş, patikada seni ne beklediğini topluluk tehlike haritasından gör, şebeke çekmediğinde de işine yarayan güvenlik araçlarıyla yürü.',
    features: [
      'ZMatch: yakındaki doğrulanmış maceraperestlerle eşleş, planı birlikte kur',
      'Topluluk tehlike haritası: kaya düşmesi, çığ, sel, vahşi hayvan, kapalı patika',
      'Basılı tut SOS: ülkeye göre acil numara, acil kişilere konum, en yakın dağ kurtarma',
      '12 çevrimdışı ilk yardım rehberi: CPR, kanama, hipotermi, irtifa, yılan ısırığı',
      'Çevrimdışı harita, rota planlama, yükseklik profili, GPX içe/dışa aktarma',
      'Kütüphane: kamp alanı, tırmanış sektörü, dalış noktası, zirve, mağara, dağ evi',
      'Tırmanış veritabanı: sektör, rota, derece dönüşümü, logbook',
      'Üniversite kulüpleri: etkinlik, RSVP, .edu doğrulama, kulüp ligi',
    ],
    safety:
      'Güvenlik notu: SOS bir bildirim aracıdır, kurtarma garantisi değildir. İlk yardım içerikleri eğitim amaçlıdır; acil durumda 112.',
    closing: 'Kâşif planı ücretsiz. Pro ₺149/ay, rehberler için Pro Guide ₺399/ay.',
  },
  en: {
    title: 'Zirtan: Hiking & Camping',
    subtitle: 'Partners, hazard map, SOS',
    short: 'Find hiking partners, check the hazard map, head out with offline maps and SOS.',
    keywords: 'hiking,trail,camping,climbing,trekking,gps,offline map,sos,first aid,scuba,route',
    promo: 'New: 12 offline first-aid guides and country-aware emergency numbers. Free Explorer plan.',
    screens: [
      'Match with verified adventurers',
      'See trail hazards before you go',
      'Press and hold for SOS',
      'First aid that works offline',
      'Offline maps and GPX routes',
      'Your club’s trips in one place',
    ],
    intro:
      'Zirtan is built for going outdoors together and better prepared. Match with verified adventurers near you, see what the trail holds on a community hazard map, and carry safety tools that keep working when the signal does not.',
    features: [
      'ZMatch: match with verified adventurers nearby and plan the trip together',
      'Community hazard map: rockfall, avalanche, flood, wildlife, closed trails',
      'Press-and-hold SOS: country-aware emergency number, location to your contacts, nearest rescue',
      '12 offline first-aid guides: CPR, bleeding, hypothermia, altitude, snakebite',
      'Offline maps, route planning, elevation profile, GPX import and export',
      'Library of campsites, crags, dive sites, summits, caves and mountain huts',
      'Climbing database: sectors, routes, grade conversion, logbook',
      'University clubs: trips, RSVP, .edu verification, club league',
    ],
    safety:
      'Safety note: SOS is a notification tool, not a rescue guarantee. First-aid content is educational; in an emergency call your local number.',
    closing: 'Explorer plan is free. Pro ₺149/month, Pro Guide ₺399/month for certified guides.',
  },
  de: {
    title: 'Zirtan: Wandern & Bergsport',
    subtitle: 'Partner, Gefahrenkarte, SOS',
    short: 'Tourenpartner finden, Gefahrenkarte prüfen, mit Offline-Karten und SOS losgehen.',
    keywords: 'wandern,bergsteigen,klettern,trekking,zelten,gps,offline karte,sos,erste hilfe,tour',
    promo: 'Neu: 12 Offline-Erste-Hilfe-Leitfäden und Notrufnummern je Land. Explorer-Plan gratis.',
    screens: [
      'Verifizierte Partner in der Nähe',
      'Gefahren am Weg vorher sehen',
      'SOS: gedrückt halten',
      'Erste Hilfe ohne Empfang',
      'Offline-Karten und GPX',
      'Touren deiner Gruppe an einem Ort',
    ],
    intro:
      'Zirtan ist dafür gebaut, gemeinsam und besser vorbereitet rauszugehen. Finde verifizierte Partner in deiner Nähe, sieh auf der Gefahrenkarte der Community, was am Weg liegt, und nimm Sicherheitswerkzeuge mit, die auch ohne Empfang funktionieren.',
    features: [
      'ZMatch: verifizierte Partner in der Nähe finden und die Tour gemeinsam planen',
      'Gefahrenkarte der Community: Steinschlag, Lawine, Hochwasser, Wildtiere, Sperrungen',
      'Halte-SOS: Notrufnummer je Land, Standort an Notfallkontakte, nächste Bergrettung',
      '12 Offline-Erste-Hilfe-Leitfäden: HLW, Blutung, Unterkühlung, Höhe, Schlangenbiss',
      'Offline-Karten, Routenplanung, Höhenprofil, GPX-Import und -Export',
      'Bibliothek: Zeltplätze, Klettergebiete, Tauchplätze, Gipfel, Höhlen, Hütten',
      'Kletterdatenbank: Sektoren, Routen, Grad-Umrechnung, Logbuch',
      'Hochschulgruppen: Touren, RSVP, .edu-Verifizierung, Vereinsliga',
    ],
    safety:
      'Sicherheitshinweis: SOS ist eine Benachrichtigung, keine Rettungsgarantie. Erste-Hilfe-Inhalte dienen der Information; im Notfall 112 wählen.',
    closing: 'Explorer-Plan kostenlos. Pro ₺149/Monat, Pro Guide ₺399/Monat für Bergführer.',
  },
  ru: {
    title: 'Zirtan: походы и горы',
    subtitle: 'Попутчики, опасности, SOS',
    short: 'Найди попутчиков, посмотри карту опасностей, иди с офлайн-картой и SOS.',
    keywords: 'поход,треккинг,горы,кемпинг,скалолазание,gps,офлайн карта,sos,первая помощь',
    promo: 'Новое: 12 офлайн-инструкций первой помощи и экстренные номера по странам. План «Кашиф» бесплатный.',
    screens: [
      'Проверенные попутчики рядом',
      'Опасности на тропе заранее',
      'SOS: нажми и удерживай',
      'Первая помощь без связи',
      'Офлайн-карты и GPX',
      'Выходы клуба в одном месте',
    ],
    intro:
      'Zirtan сделан для того, чтобы выходить в горы вместе и подготовленным. Находи проверенных попутчиков рядом, смотри на карте опасностей, что ждёт на тропе, и бери с собой инструменты, которые работают без связи.',
    features: [
      'ZMatch: проверенные попутчики рядом и совместное планирование выхода',
      'Карта опасностей от сообщества: камнепад, лавина, паводок, звери, закрытая тропа',
      'SOS удержанием: номер по стране, координаты экстренным контактам, ближайшие спасатели',
      '12 офлайн-инструкций первой помощи: СЛР, кровотечение, гипотермия, высота, укус змеи',
      'Офлайн-карты, планировщик маршрутов, профиль высот, импорт и экспорт GPX',
      'Библиотека: кемпинги, скалы, дайв-сайты, вершины, пещеры, приюты',
      'База скалолазания: сектора, маршруты, конвертер категорий, логбук',
      'Студенческие клубы: выходы, RSVP, .edu-подтверждение, лига клубов',
    ],
    safety:
      'О безопасности: SOS — способ оповещения, а не гарантия спасения. Материалы по первой помощи носят образовательный характер; в экстренной ситуации звоните 112.',
    closing: 'План «Кашиф» бесплатный. Pro — ₺149/мес, Pro Guide для гидов — ₺399/мес.',
  },
  ne: {
    title: 'Zirtan: पदयात्रा र क्याम्प',
    subtitle: 'साथी, जोखिम नक्सा, SOS',
    short: 'पदयात्रा साथी खोज्नुहोस्, जोखिम नक्सा हेर्नुहोस्, अफलाइन नक्सासँग हिँड्नुहोस्।',
    keywords: 'पदयात्रा,हिमाल,क्याम्प,ट्रेक,gps,अफलाइन नक्सा,sos,प्राथमिक उपचार,रुट',
    promo: 'नयाँ: १२ अफलाइन प्राथमिक उपचार निर्देशिका र देशअनुसार आपत्कालीन नम्बर। नि:शुल्क योजना उपलब्ध।',
    screens: [
      'नजिकैका प्रमाणित साथीहरू',
      'बाटोको जोखिम पहिल्यै हेर्नुहोस्',
      'SOS: थिचिराख्नुहोस्',
      'नेटवर्क बिनै प्राथमिक उपचार',
      'अफलाइन नक्सा र GPX',
      'क्लबका कार्यक्रम एकै ठाउँमा',
    ],
    intro:
      'Zirtan सँगै र राम्रो तयारीसाथ हिँड्नका लागि बनेको हो। नजिकैका प्रमाणित पदयात्रीसँग जोडिनुहोस्, समुदायको जोखिम नक्सामा बाटोको अवस्था हेर्नुहोस्, र नेटवर्क नहुँदा पनि काम गर्ने सुरक्षा साधन बोक्नुहोस्।',
    features: [
      'ZMatch: नजिकैका प्रमाणित पदयात्रीसँग मिलान र सँगै योजना',
      'समुदाय जोखिम नक्सा: ढुङ्गा खस्ने, हिमपहिरो, बाढी, जनावर, बन्द बाटो',
      'SOS: देशअनुसार आपत्कालीन नम्बर, आफन्तलाई स्थान, नजिकको उद्धार केन्द्र',
      '१२ अफलाइन प्राथमिक उपचार निर्देशिका: CPR, रक्तस्राव, हाइपोथर्मिया, उचाइ, सर्पदंश',
      'अफलाइन नक्सा, रुट योजना, उचाइ प्रोफाइल, GPX आयात–निर्यात',
      'पुस्तकालय: क्याम्प, चट्टान, डुबुल्की स्थल, शिखर, गुफा, पहाडी घर',
      'चट्टान आरोहण डाटाबेस: सेक्टर, रुट, ग्रेड रूपान्तरण, लगबुक',
      'विश्वविद्यालय क्लब: कार्यक्रम, RSVP, .edu प्रमाणीकरण, क्लब लिग',
    ],
    safety:
      'सुरक्षा सूचना: SOS सूचना दिने साधन हो, उद्धारको ग्यारेन्टी होइन। प्राथमिक उपचार सामग्री शैक्षिक हो; आपत्कालमा स्थानीय नम्बरमा फोन गर्नुहोस्।',
    closing: 'नि:शुल्क योजना उपलब्ध। Pro ₺149/महिना, गाइडका लागि Pro Guide ₺399/महिना।',
  },
  fr: {
    title: 'Zirtan : rando & bivouac',
    subtitle: 'Partenaires, dangers, SOS',
    short: 'Trouve des partenaires, vois les dangers, pars avec des cartes hors ligne.',
    keywords: 'randonnée,trek,bivouac,escalade,gps,carte hors ligne,sos,premiers secours,itinéraire',
    promo: 'Nouveau : 12 guides de premiers secours hors ligne et numéros d’urgence par pays. Plan gratuit.',
    screens: [
      'Des partenaires vérifiés près de toi',
      'Les dangers du sentier à l’avance',
      'SOS : appui long',
      'Premiers secours hors réseau',
      'Cartes hors ligne et GPX',
      'Les sorties du club au même endroit',
    ],
    intro:
      'Zirtan est fait pour sortir ensemble et mieux préparé. Trouve des partenaires vérifiés près de chez toi, vois ce qui t’attend sur le sentier grâce à la carte des dangers de la communauté, et emporte des outils de sécurité qui fonctionnent sans réseau.',
    features: [
      'ZMatch : trouve des partenaires vérifiés à proximité et planifiez ensemble',
      'Carte des dangers : chutes de pierres, avalanche, crue, faune, sentier fermé',
      'SOS appui long : numéro d’urgence du pays, position aux contacts, secours le plus proche',
      '12 guides de premiers secours hors ligne : RCP, hémorragie, hypothermie, altitude, morsure',
      'Cartes hors ligne, planification d’itinéraire, profil altimétrique, GPX',
      'Bibliothèque : bivouacs, falaises, sites de plongée, sommets, grottes, refuges',
      'Base d’escalade : secteurs, voies, conversion de cotations, carnet',
      'Clubs universitaires : sorties, inscriptions, vérification .edu, classement',
    ],
    safety:
      'Sécurité : le SOS est un outil d’alerte, pas une garantie de secours. Les contenus de premiers secours sont informatifs ; en urgence, appelez le 112.',
    closing: 'Plan Explorer gratuit. Pro ₺149/mois, Pro Guide ₺399/mois pour les guides.',
  },
  es: {
    title: 'Zirtan: senderismo y montaña',
    subtitle: 'Compañeros, peligros, SOS',
    short: 'Encuentra compañeros, mira el mapa de peligros y sal con mapas sin conexión.',
    keywords: 'senderismo,montaña,acampada,escalada,gps,mapa sin conexión,sos,primeros auxilios',
    promo: 'Nuevo: 12 guías de primeros auxilios sin conexión y números de emergencia por país. Plan gratis.',
    screens: [
      'Compañeros verificados cerca de ti',
      'Peligros del sendero por adelantado',
      'SOS: mantén pulsado',
      'Primeros auxilios sin cobertura',
      'Mapas sin conexión y GPX',
      'Las salidas del club en un sitio',
    ],
    intro:
      'Zirtan está hecho para salir en compañía y mejor preparado. Encuentra montañeros verificados cerca, mira en el mapa de peligros de la comunidad lo que hay en la ruta y lleva herramientas de seguridad que siguen funcionando sin cobertura.',
    features: [
      'ZMatch: compañeros verificados cerca y planificación conjunta de la salida',
      'Mapa de peligros: desprendimientos, aludes, crecidas, fauna, sendero cerrado',
      'SOS manteniendo pulsado: número del país, ubicación a tus contactos, rescate más cercano',
      '12 guías de primeros auxilios sin conexión: RCP, hemorragia, hipotermia, altura, mordedura',
      'Mapas sin conexión, planificación de rutas, perfil de altitud, GPX',
      'Biblioteca: campings, escuelas de escalada, buceo, cumbres, cuevas y refugios',
      'Base de escalada: sectores, vías, conversión de grados, libro de vías',
      'Clubes universitarios: salidas, inscripción, verificación .edu, liga de clubes',
    ],
    safety:
      'Aviso de seguridad: el SOS es una herramienta de aviso, no una garantía de rescate. Los primeros auxilios son informativos; en una emergencia llama al 112.',
    closing: 'Plan Explorer gratis. Pro ₺149/mes, Pro Guide ₺399/mes para guías.',
  },
  it: {
    title: 'Zirtan: trekking e montagna',
    subtitle: 'Compagni, pericoli, SOS',
    short: 'Trova compagni di cammino, guarda la mappa dei pericoli, esci con mappe offline.',
    keywords: 'trekking,montagna,campeggio,arrampicata,gps,mappa offline,sos,primo soccorso,sentiero',
    promo: 'Novità: 12 guide di primo soccorso offline e numeri di emergenza per Paese. Piano gratuito.',
    screens: [
      'Compagni verificati vicino a te',
      'Pericoli del sentiero in anticipo',
      'SOS: tieni premuto',
      'Primo soccorso senza campo',
      'Mappe offline e GPX',
      'Le uscite del club in un posto',
    ],
    intro:
      'Zirtan nasce per andare in montagna insieme e più preparati. Trova compagni verificati vicino a te, guarda sulla mappa dei pericoli della comunità cosa ti aspetta sul sentiero e porta con te strumenti di sicurezza che funzionano anche senza campo.',
    features: [
      'ZMatch: compagni verificati vicini e pianificazione condivisa dell’uscita',
      'Mappa dei pericoli: caduta sassi, valanghe, piene, fauna, sentiero chiuso',
      'SOS con pressione prolungata: numero del Paese, posizione ai contatti, soccorso più vicino',
      '12 guide di primo soccorso offline: RCP, emorragia, ipotermia, quota, morso di vipera',
      'Mappe offline, pianificazione itinerari, profilo altimetrico, GPX',
      'Biblioteca: campeggi, falesie, siti di immersione, cime, grotte e rifugi',
      'Database arrampicata: settori, vie, conversione dei gradi, logbook',
      'Gruppi universitari: uscite, iscrizioni, verifica .edu, classifica',
    ],
    safety:
      'Nota di sicurezza: l’SOS è uno strumento di allerta, non una garanzia di soccorso. I contenuti di primo soccorso sono informativi; in emergenza chiama il 112.',
    closing: 'Piano Explorer gratuito. Pro ₺149/mese, Pro Guide ₺399/mese per le guide.',
  },
  pt: {
    title: 'Zirtan: trilhas e montanha',
    subtitle: 'Parceiros, perigos, SOS',
    short: 'Encontre parceiros de trilha, veja o mapa de perigos e saia com mapas offline.',
    keywords: 'trilha,montanha,camping,escalada,gps,mapa offline,sos,primeiros socorros,rota',
    promo: 'Novo: 12 guias de primeiros socorros offline e números de emergência por país. Plano grátis.',
    screens: [
      'Parceiros verificados perto de você',
      'Perigos da trilha antes de sair',
      'SOS: pressione e segure',
      'Primeiros socorros sem sinal',
      'Mapas offline e GPX',
      'As saídas do clube num só lugar',
    ],
    intro:
      'O Zirtan foi feito para sair acompanhado e mais preparado. Encontre aventureiros verificados por perto, veja no mapa de perigos da comunidade o que espera na trilha e leve ferramentas de segurança que continuam funcionando sem sinal.',
    features: [
      'ZMatch: parceiros verificados por perto e planejamento conjunto da saída',
      'Mapa de perigos: queda de pedras, avalanche, cheia, fauna, trilha fechada',
      'SOS pressionando: número do país, localização para contatos, resgate mais próximo',
      '12 guias de primeiros socorros offline: RCP, hemorragia, hipotermia, altitude, picada',
      'Mapas offline, planejamento de rota, perfil de elevação, GPX',
      'Biblioteca: campings, setores de escalada, mergulho, cumes, cavernas e refúgios',
      'Base de escalada: setores, vias, conversão de graus, logbook',
      'Clubes universitários: saídas, inscrição, verificação .edu, liga de clubes',
    ],
    safety:
      'Aviso de segurança: o SOS é um aviso, não uma garantia de resgate. Os conteúdos de primeiros socorros são educativos; em emergência, ligue para o número local.',
    closing: 'Plano Explorer grátis. Pro ₺149/mês, Pro Guide ₺399/mês para guias.',
  },
  ka: {
    title: 'Zirtan: ლაშქრობა და მთა',
    subtitle: 'პარტნიორი, საფრთხე, SOS',
    short: 'იპოვე თანამგზავრი, ნახე საფრთხეების რუკა და გადი ოფლაინ რუკითა და SOS-ით.',
    keywords: 'ლაშქრობა,მთა,კემპინგი,ალპინიზმი,gps,ოფლაინ რუკა,sos,პირველი დახმარება',
    promo: 'ახალი: 12 ოფლაინ სახელმძღვანელო პირველი დახმარებისთვის და ქვეყნის მიხედვით საგანგებო ნომრები.',
    screens: [
      'დადასტურებული თანამგზავრები',
      'ბილიკის საფრთხეები წინასწარ',
      'SOS: დააჭირე და გეჭიროს',
      'პირველი დახმარება ქსელის გარეშე',
      'ოფლაინ რუკები და GPX',
      'კლუბის გასვლები ერთ ადგილას',
    ],
    intro:
      'Zirtan შექმნილია იმისთვის, რომ ბუნებაში ერთად და უკეთ მომზადებული გახვიდე. იპოვე ახლოს მყოფი დადასტურებული მოლაშქრეები, ნახე საზოგადოების საფრთხეების რუკაზე რა გელოდება ბილიკზე და წაიღე უსაფრთხოების ხელსაწყოები, რომლებიც ქსელის გარეშეც მუშაობს.',
    features: [
      'ZMatch: ახლოს მყოფი დადასტურებული მოლაშქრეები და ერთობლივი დაგეგმვა',
      'საფრთხეების რუკა: ქვათაცვენა, ზვავი, წყალდიდობა, ცხოველები, დაკეტილი ბილიკი',
      'SOS: ქვეყნის საგანგებო ნომერი, ლოკაცია კონტაქტებს, უახლოესი სამაშველო',
      '12 ოფლაინ ინსტრუქცია: CPR, სისხლდენა, ჰიპოთერმია, სიმაღლე, გველის ნაკბენი',
      'ოფლაინ რუკები, მარშრუტის დაგეგმვა, სიმაღლის პროფილი, GPX',
      'ბიბლიოთეკა: კემპინგი, კლდეები, ჩაძირვის ადგილები, მწვერვალები, გამოქვაბულები',
      'ალპინიზმის ბაზა: სექტორები, მარშრუტები, კატეგორიების გადაყვანა, ლოგბუკი',
      'საუნივერსიტეტო კლუბები: გასვლები, RSVP, .edu დადასტურება, ლიგა',
    ],
    safety:
      'უსაფრთხოება: SOS შეტყობინების საშუალებაა და არა სამაშველო გარანტია. პირველი დახმარების მასალა საგანმანათლებლოა; საგანგებო შემთხვევაში დარეკე 112-ზე.',
    closing: 'Explorer გეგმა უფასოა. Pro ₺149/თვე, გიდებისთვის Pro Guide ₺399/თვე.',
  },
  pl: {
    title: 'Zirtan: górskie szlaki',
    subtitle: 'Partnerzy, zagrożenia, SOS',
    short: 'Znajdź partnerów, sprawdź mapę zagrożeń i wyjdź z mapami offline oraz SOS.',
    keywords: 'szlak,góry,kemping,wspinaczka,gps,mapa offline,sos,pierwsza pomoc,trekking',
    promo: 'Nowość: 12 poradników pierwszej pomocy offline i numery alarmowe według kraju. Plan darmowy.',
    screens: [
      'Zweryfikowani partnerzy w pobliżu',
      'Zagrożenia na szlaku z wyprzedzeniem',
      'SOS: naciśnij i przytrzymaj',
      'Pierwsza pomoc bez zasięgu',
      'Mapy offline i GPX',
      'Wyjazdy klubu w jednym miejscu',
    ],
    intro:
      'Zirtan powstał po to, żeby wychodzić w góry razem i lepiej przygotowanym. Znajdź zweryfikowanych partnerów w pobliżu, zobacz na społecznościowej mapie zagrożeń, co czeka na szlaku, i zabierz narzędzia, które działają bez zasięgu.',
    features: [
      'ZMatch: zweryfikowani partnerzy w pobliżu i wspólne planowanie wyjścia',
      'Mapa zagrożeń: obrywy skalne, lawiny, powodzie, zwierzęta, zamknięty szlak',
      'SOS przytrzymaniem: numer alarmowy kraju, lokalizacja do kontaktów, najbliższy ratunek',
      '12 poradników pierwszej pomocy offline: RKO, krwotok, hipotermia, wysokość, ukąszenie',
      'Mapy offline, planowanie tras, profil wysokości, import i eksport GPX',
      'Biblioteka: kempingi, rejony wspinaczkowe, nurkowanie, szczyty, jaskinie, schroniska',
      'Baza wspinaczkowa: sektory, drogi, przeliczanie skal, logbook',
      'Kluby uczelniane: wyjazdy, zapisy, weryfikacja .edu, liga klubów',
    ],
    safety:
      'Uwaga: SOS to narzędzie powiadamiania, nie gwarancja ratunku. Materiały o pierwszej pomocy mają charakter edukacyjny; w nagłym wypadku dzwoń pod 112.',
    closing: 'Plan Explorer za darmo. Pro ₺149/mies., Pro Guide ₺399/mies. dla przewodników.',
  },
  cs: {
    title: 'Zirtan: turistika a hory',
    subtitle: 'Parťáci, nebezpečí, SOS',
    short: 'Najdi parťáky na túru, zkontroluj mapu nebezpečí a vyraz s offline mapami.',
    keywords: 'turistika,hory,kemping,lezení,gps,offline mapa,sos,první pomoc,trasa,trek',
    promo: 'Novinka: 12 offline návodů první pomoci a tísňová čísla podle země. Plán Explorer zdarma.',
    screens: [
      'Ověření parťáci ve tvém okolí',
      'Nebezpečí na trase předem',
      'SOS: stiskni a drž',
      'První pomoc bez signálu',
      'Offline mapy a GPX',
      'Akce klubu na jednom místě',
    ],
    intro:
      'Zirtan je pro ty, kdo chtějí do hor společně a připravenější. Najdi ověřené parťáky poblíž, podívej se na komunitní mapu nebezpečí, co tě na trase čeká, a vezmi si nástroje, které fungují i bez signálu.',
    features: [
      'ZMatch: ověření parťáci v okolí a společné plánování túry',
      'Komunitní mapa nebezpečí: padání kamení, laviny, povodně, zvěř, uzavřená cesta',
      'SOS podržením: tísňové číslo dané země, poloha kontaktům, nejbližší záchrana',
      '12 offline návodů první pomoci: KPR, krvácení, podchlazení, výška, uštknutí',
      'Offline mapy, plánování trasy, výškový profil, import a export GPX',
      'Knihovna: kempy, lezecké oblasti, potápění, vrcholy, jeskyně a chaty',
      'Lezecká databáze: sektory, cesty, převod stupnic, logbook',
      'Univerzitní kluby: akce, přihlášky, ověření .edu, liga klubů',
    ],
    safety:
      'Bezpečnost: SOS je nástroj upozornění, ne záruka záchrany. Obsah první pomoci je vzdělávací; v nouzi volej 112.',
    closing: 'Plán Explorer zdarma. Pro ₺149/měsíc, Pro Guide ₺399/měsíc pro průvodce.',
  },
  el: {
    title: 'Zirtan: πεζοπορία & βουνό',
    subtitle: 'Παρέα, κίνδυνοι, SOS',
    short: 'Βρες παρέα, δες τον χάρτη κινδύνων και βγες με offline χάρτες και SOS.',
    keywords: 'πεζοπορία,βουνό,κάμπινγκ,αναρρίχηση,gps,offline χάρτης,sos,πρώτες βοήθειες',
    promo: 'Νέο: 12 offline οδηγοί πρώτων βοηθειών και αριθμοί έκτακτης ανάγκης ανά χώρα. Δωρεάν πλάνο.',
    screens: [
      'Επαληθευμένη παρέα κοντά σου',
      'Κίνδυνοι στο μονοπάτι εκ των προτέρων',
      'SOS: πάτα παρατεταμένα',
      'Πρώτες βοήθειες χωρίς σήμα',
      'Offline χάρτες και GPX',
      'Οι εξορμήσεις του συλλόγου',
    ],
    intro:
      'Το Zirtan φτιάχτηκε για να βγαίνεις στη φύση με παρέα και καλύτερα προετοιμασμένος. Βρες επαληθευμένους πεζοπόρους κοντά σου, δες στον κοινοτικό χάρτη κινδύνων τι σε περιμένει στο μονοπάτι και πάρε μαζί σου εργαλεία που δουλεύουν και χωρίς σήμα.',
    features: [
      'ZMatch: επαληθευμένοι σύντροφοι κοντά σου και κοινός σχεδιασμός',
      'Χάρτης κινδύνων: πτώση βράχων, χιονοστιβάδα, πλημμύρα, άγρια ζώα, κλειστό μονοπάτι',
      'SOS με παρατεταμένο πάτημα: αριθμός της χώρας, θέση στις επαφές, πλησιέστερη διάσωση',
      '12 offline οδηγοί πρώτων βοηθειών: ΚΑΡΠΑ, αιμορραγία, υποθερμία, υψόμετρο, δάγκωμα',
      'Offline χάρτες, σχεδιασμός διαδρομής, προφίλ υψομέτρου, GPX',
      'Βιβλιοθήκη: κάμπινγκ, πεδία αναρρίχησης, καταδύσεις, κορυφές, σπήλαια, καταφύγια',
      'Βάση αναρρίχησης: τομείς, διαδρομές, μετατροπή βαθμών, logbook',
      'Πανεπιστημιακοί σύλλογοι: εξορμήσεις, δηλώσεις, επαλήθευση .edu, λίγκα',
    ],
    safety:
      'Ασφάλεια: το SOS είναι εργαλείο ειδοποίησης, όχι εγγύηση διάσωσης. Το υλικό πρώτων βοηθειών είναι ενημερωτικό· σε έκτακτη ανάγκη καλέστε το 112.',
    closing: 'Πλάνο Explorer δωρεάν. Pro ₺149/μήνα, Pro Guide ₺399/μήνα για οδηγούς.',
  },
  nl: {
    title: 'Zirtan: wandelen & bergen',
    subtitle: 'Maatjes, gevaren, SOS',
    short: 'Vind wandelmaatjes, bekijk de gevarenkaart en ga op pad met offline kaarten.',
    keywords: 'wandelen,bergen,kamperen,klimmen,gps,offline kaart,sos,eerste hulp,route,trektocht',
    promo: 'Nieuw: 12 offline eerstehulpgidsen en alarmnummers per land. Explorer-abonnement gratis.',
    screens: [
      'Geverifieerde maatjes in de buurt',
      'Gevaren op het pad vooraf',
      'SOS: ingedrukt houden',
      'Eerste hulp zonder bereik',
      'Offline kaarten en GPX',
      'Tochten van je club bij elkaar',
    ],
    intro:
      'Zirtan is gemaakt om samen en beter voorbereid naar buiten te gaan. Vind geverifieerde wandelaars in de buurt, zie op de gevarenkaart van de community wat er op het pad ligt en neem gereedschap mee dat ook zonder bereik werkt.',
    features: [
      'ZMatch: geverifieerde maatjes in de buurt en samen plannen',
      'Gevarenkaart: steenslag, lawine, hoogwater, wilde dieren, afgesloten pad',
      'SOS ingedrukt houden: alarmnummer per land, locatie naar contacten, dichtstbijzijnde redding',
      '12 offline eerstehulpgidsen: reanimatie, bloeding, onderkoeling, hoogte, slangenbeet',
      'Offline kaarten, routeplanning, hoogteprofiel, GPX importeren en exporteren',
      'Bibliotheek: campings, klimgebieden, duikstekken, toppen, grotten en hutten',
      'Klimdatabase: sectoren, routes, graadconversie, logboek',
      'Studentenclubs: tochten, aanmelding, .edu-verificatie, clubcompetitie',
    ],
    safety:
      'Veiligheid: SOS is een meldmiddel, geen reddingsgarantie. Eerstehulpinhoud is educatief; bel bij nood 112.',
    closing: 'Explorer gratis. Pro ₺149/maand, Pro Guide ₺399/maand voor gidsen.',
  },
  sv: {
    title: 'Zirtan: vandring och fjäll',
    subtitle: 'Sällskap, faror, SOS',
    short: 'Hitta vandringssällskap, kolla farokartan och ge dig ut med offlinekartor.',
    keywords: 'vandring,fjäll,camping,klättring,gps,offlinekarta,sos,första hjälpen,led,trekking',
    promo: 'Nytt: 12 offlineguider i första hjälpen och nödnummer per land. Explorer-planen är gratis.',
    screens: [
      'Verifierat sällskap nära dig',
      'Faror på leden i förväg',
      'SOS: tryck och håll in',
      'Första hjälpen utan täckning',
      'Offlinekartor och GPX',
      'Klubbens turer på ett ställe',
    ],
    intro:
      'Zirtan är byggt för att ge sig ut tillsammans och bättre förberedd. Hitta verifierade vandrare nära dig, se på communityns farokarta vad som väntar på leden och ta med verktyg som fungerar även utan täckning.',
    features: [
      'ZMatch: verifierat sällskap i närheten och gemensam planering',
      'Farokarta från communityn: stenras, lavin, översvämning, vilda djur, stängd led',
      'SOS med långtryck: nödnummer per land, position till kontakter, närmaste fjällräddning',
      '12 offlineguider i första hjälpen: HLR, blödning, hypotermi, höjd, ormbett',
      'Offlinekartor, ruttplanering, höjdprofil, GPX-import och -export',
      'Bibliotek: campingplatser, klätterklippor, dykplatser, toppar, grottor och stugor',
      'Klätterdatabas: sektorer, leder, gradkonvertering, loggbok',
      'Studentklubbar: turer, anmälan, .edu-verifiering, klubbliga',
    ],
    safety:
      'Säkerhet: SOS är ett larmverktyg, inte en garanti för räddning. Innehållet om första hjälpen är utbildning; ring 112 i nödläge.',
    closing: 'Explorer är gratis. Pro ₺149/månad, Pro Guide ₺399/månad för guider.',
  },
  nb: {
    title: 'Zirtan: tur og fjell',
    subtitle: 'Turfølge, farer, SOS',
    short: 'Finn turfølge, sjekk farekartet og dra ut med offlinekart og SOS.',
    keywords: 'fottur,fjell,telttur,klatring,gps,offlinekart,sos,førstehjelp,sti,trekking',
    promo: 'Nytt: 12 førstehjelpsguider offline og nødnumre per land. Explorer-planen er gratis.',
    screens: [
      'Verifisert turfølge i nærheten',
      'Farer på stien på forhånd',
      'SOS: trykk og hold',
      'Førstehjelp uten dekning',
      'Offlinekart og GPX',
      'Turene til klubben samlet',
    ],
    intro:
      'Zirtan er laget for å komme seg ut sammen og bedre forberedt. Finn verifiserte turfolk i nærheten, se på farekartet fra fellesskapet hva som venter på stien, og ta med verktøy som virker uten dekning.',
    features: [
      'ZMatch: verifisert turfølge i nærheten og felles planlegging',
      'Farekart fra fellesskapet: steinsprang, snøskred, flom, dyr, stengt sti',
      'SOS med langt trykk: nødnummer per land, posisjon til kontakter, nærmeste redning',
      '12 førstehjelpsguider offline: HLR, blødning, hypotermi, høyde, slangebitt',
      'Offlinekart, ruteplanlegging, høydeprofil, GPX inn og ut',
      'Bibliotek: teltplasser, klatrefelt, dykkesteder, topper, huler og hytter',
      'Klatredatabase: sektorer, ruter, gradkonvertering, loggbok',
      'Studentklubber: turer, påmelding, .edu-verifisering, klubbliga',
    ],
    safety:
      'Sikkerhet: SOS varsler, det garanterer ikke redning. Førstehjelpsinnholdet er informasjon; ring 113 ved nød.',
    closing: 'Explorer er gratis. Pro ₺149/måned, Pro Guide ₺399/måned for guider.',
  },
  ja: {
    title: 'Zirtan: 登山とキャンプ',
    subtitle: '仲間・危険マップ・SOS',
    short: '登山の仲間を見つけ、危険マップを確認し、オフライン地図とSOSで出かけよう。',
    keywords: '登山,ハイキング,キャンプ,クライミング,gps,オフライン地図,sos,応急処置,トレッキング',
    promo: '新機能: オフライン応急処置ガイド12種と国別の緊急番号。Explorerプランは無料です。',
    screens: [
      '近くの認証済みの仲間',
      '登山道の危険を事前に確認',
      'SOS: 長押しで発信',
      '圏外でも使える応急処置',
      'オフライン地図とGPX',
      'クラブの山行を一か所に',
    ],
    intro:
      'Zirtanは、仲間と一緒に、より備えて山に入るためのアプリです。近くの認証済みの登山者と出会い、コミュニティの危険マップで登山道の状況を確認し、電波がなくても使える安全機能を持って歩けます。',
    features: [
      'ZMatch: 近くの認証済み登山者とマッチングし、計画を一緒に立てる',
      'コミュニティ危険マップ: 落石、雪崩、増水、野生動物、通行止め',
      '長押しSOS: 国別の緊急番号、緊急連絡先への位置情報、最寄りの山岳救助',
      'オフライン応急処置ガイド12種: 心肺蘇生、出血、低体温症、高山病、蛇咬傷',
      'オフライン地図、ルート作成、標高プロファイル、GPXの入出力',
      'ライブラリ: キャンプ場、岩場、ダイビング、山頂、洞窟、山小屋',
      'クライミングDB: セクター、ルート、グレード換算、ログブック',
      '大学の山岳部: 山行、参加登録、.edu認証、クラブリーグ',
    ],
    safety:
      '安全に関する注意: SOSは通知手段であり、救助を保証するものではありません。応急処置の内容は教育目的です。緊急時は現地の緊急番号（日本は119）に連絡してください。',
    closing: 'Explorerプランは無料。Pro 月額₺149、ガイド向けPro Guide 月額₺399。',
  },
  zh: {
    title: 'Zirtan：徒步与露营',
    subtitle: '找伙伴・风险地图・SOS',
    short: '找到徒步伙伴，查看路线风险地图，带着离线地图和SOS出发。',
    keywords: '徒步,登山,露营,攀岩,gps,离线地图,sos,急救,路线,户外',
    promo: '新增：12份离线急救指南与按国家显示的紧急号码。探索者方案免费。',
    screens: [
      '附近经过验证的伙伴',
      '提前看到路线上的风险',
      'SOS：长按发送',
      '没信号也能用的急救',
      '离线地图与GPX',
      '社团活动集中在一处',
    ],
    intro:
      'Zirtan 让你结伴出行、准备更充分。与附近经过验证的户外爱好者匹配，在社区风险地图上看清前方路线的情况，并带上没有信号也能使用的安全工具。',
    features: [
      'ZMatch：匹配附近经过验证的伙伴，一起制定计划',
      '社区风险地图：落石、雪崩、洪水、野生动物、封闭路段',
      '长按SOS：按国家显示紧急号码、向紧急联系人发送位置、最近的山地救援',
      '12份离线急救指南：心肺复苏、出血、失温、高原反应、蛇咬伤',
      '离线地图、路线规划、海拔剖面、GPX导入导出',
      '资料库：营地、岩场、潜点、山顶、洞穴与山屋',
      '攀岩数据库：区域、线路、难度换算、攀登记录',
      '高校社团：活动、报名、.edu 验证、社团积分榜',
    ],
    safety:
      '安全提示：SOS 是通知工具，不能保证获得救援。急救内容仅供学习参考；紧急情况请拨打当地急救电话。',
    closing: '探索者方案免费。Pro 每月₺149，向导版 Pro Guide 每月₺399。',
  },
  ko: {
    title: 'Zirtan: 등산과 캠핑',
    subtitle: '동행・위험 지도・SOS',
    short: '등산 동행을 찾고 위험 지도를 확인한 뒤 오프라인 지도와 SOS로 출발하세요.',
    keywords: '등산,하이킹,캠핑,클라이밍,gps,오프라인 지도,sos,응급처치,트레킹,코스',
    promo: '새로워진 기능: 오프라인 응급처치 가이드 12종과 국가별 긴급 번호. 익스플로러 요금제 무료.',
    screens: [
      '가까운 인증된 동행',
      '코스 위험을 미리 확인',
      'SOS: 길게 누르기',
      '신호 없어도 되는 응급처치',
      '오프라인 지도와 GPX',
      '동아리 산행을 한곳에',
    ],
    intro:
      'Zirtan은 함께, 더 잘 준비해서 산에 가기 위한 앱입니다. 가까운 곳의 인증된 산행 동행을 찾고, 커뮤니티 위험 지도로 코스 상황을 확인하고, 신호가 없어도 작동하는 안전 도구를 챙기세요.',
    features: [
      'ZMatch: 가까운 인증 동행 매칭과 공동 산행 계획',
      '커뮤니티 위험 지도: 낙석, 눈사태, 범람, 야생동물, 폐쇄 구간',
      '길게 누르는 SOS: 국가별 긴급 번호, 비상 연락처에 위치, 가까운 산악구조',
      '오프라인 응급처치 가이드 12종: 심폐소생술, 출혈, 저체온증, 고산증, 뱀 물림',
      '오프라인 지도, 경로 계획, 고도 프로필, GPX 가져오기·내보내기',
      '라이브러리: 캠핑장, 암장, 다이빙 포인트, 정상, 동굴, 산장',
      '클라이밍 데이터베이스: 섹터, 루트, 등급 변환, 로그북',
      '대학 동아리: 산행, 참가 신청, .edu 인증, 동아리 리그',
    ],
    safety:
      '안전 안내: SOS는 알림 도구이며 구조를 보장하지 않습니다. 응급처치 내용은 교육 목적입니다. 위급 시 현지 긴급 번호로 연락하세요.',
    closing: '익스플로러 요금제 무료. Pro 월 ₺149, 가이드용 Pro Guide 월 ₺399.',
  },
  hi: {
    title: 'Zirtan: ट्रेकिंग और कैंपिंग',
    subtitle: 'साथी, जोखिम मानचित्र, SOS',
    short: 'ट्रेकिंग साथी खोजें, जोखिम मानचित्र देखें और ऑफ़लाइन नक्शे व SOS के साथ निकलें।',
    keywords: 'ट्रेकिंग,पहाड़,कैंपिंग,क्लाइंबिंग,gps,ऑफलाइन नक्शा,sos,प्राथमिक चिकित्सा,रूट',
    promo: 'नया: 12 ऑफ़लाइन प्राथमिक चिकित्सा गाइड और देश के अनुसार आपातकालीन नंबर। एक्सप्लोरर प्लान मुफ़्त।',
    screens: [
      'पास के सत्यापित साथी',
      'रास्ते के जोखिम पहले से देखें',
      'SOS: दबाकर रखें',
      'बिना नेटवर्क प्राथमिक चिकित्सा',
      'ऑफ़लाइन नक्शे और GPX',
      'क्लब की यात्राएँ एक जगह',
    ],
    intro:
      'Zirtan इसलिए बना है कि आप साथ मिलकर और बेहतर तैयारी के साथ निकलें। पास के सत्यापित ट्रेकर्स से जुड़ें, सामुदायिक जोखिम मानचित्र पर देखें कि रास्ते में क्या है, और ऐसे सुरक्षा साधन साथ रखें जो नेटवर्क न होने पर भी काम करें।',
    features: [
      'ZMatch: पास के सत्यापित साथी और साथ मिलकर योजना',
      'सामुदायिक जोखिम मानचित्र: पत्थर गिरना, हिमस्खलन, बाढ़, वन्यजीव, बंद रास्ता',
      'दबाकर रखें SOS: देश अनुसार आपातकालीन नंबर, संपर्कों को लोकेशन, निकटतम बचाव दल',
      '12 ऑफ़लाइन प्राथमिक चिकित्सा गाइड: CPR, रक्तस्राव, हाइपोथर्मिया, ऊँचाई, सर्पदंश',
      'ऑफ़लाइन नक्शे, रूट योजना, ऊँचाई प्रोफ़ाइल, GPX आयात–निर्यात',
      'लाइब्रेरी: कैंपसाइट, क्रैग, डाइव साइट, चोटियाँ, गुफाएँ और पर्वत आश्रय',
      'क्लाइंबिंग डेटाबेस: सेक्टर, रूट, ग्रेड रूपांतरण, लॉगबुक',
      'विश्वविद्यालय क्लब: यात्राएँ, RSVP, .edu सत्यापन, क्लब लीग',
    ],
    safety:
      'सुरक्षा सूचना: SOS सूचना देने का साधन है, बचाव की गारंटी नहीं। प्राथमिक चिकित्सा सामग्री शैक्षिक है; आपात स्थिति में स्थानीय नंबर पर कॉल करें।',
    closing: 'एक्सप्लोरर प्लान मुफ़्त। Pro ₺149/माह, गाइड के लिए Pro Guide ₺399/माह।',
  },
  ar: {
    title: 'Zirtan: المشي والتخييم',
    subtitle: 'رفاق، خريطة مخاطر، SOS',
    short: 'اعثر على رفاق للمشي، راجع خريطة المخاطر، واخرج بخرائط دون اتصال وزر SOS.',
    keywords: 'المشي,الجبال,التخييم,التسلق,gps,خريطة دون اتصال,sos,إسعافات أولية,مسار',
    promo: 'جديد: 12 دليل إسعافات أولية دون اتصال وأرقام طوارئ حسب الدولة. خطة Explorer مجانية.',
    screens: [
      'رفاق موثوقون بالقرب منك',
      'مخاطر المسار قبل انطلاقك',
      'SOS: اضغط مطولاً',
      'إسعافات أولية دون تغطية',
      'خرائط دون اتصال وGPX',
      'رحلات النادي في مكان واحد',
    ],
    intro:
      'صُمم Zirtan للخروج معاً واستعداداً أفضل. اعثر على مغامرين موثوقين قريبين منك، وشاهد على خريطة المخاطر المجتمعية ما ينتظرك على المسار، واحمل أدوات سلامة تعمل حتى دون تغطية.',
    features: [
      'ZMatch: مطابقة مع مغامرين موثوقين قريبين وتخطيط الرحلة معاً',
      'خريطة المخاطر المجتمعية: سقوط صخور، انهيار ثلجي، فيضان، حيوانات، مسار مغلق',
      'زر SOS بالضغط المطول: رقم الطوارئ حسب الدولة، الموقع لجهات الاتصال، أقرب فريق إنقاذ',
      '12 دليل إسعافات أولية دون اتصال: الإنعاش، النزيف، انخفاض الحرارة، الارتفاع، لدغة الأفعى',
      'خرائط دون اتصال، تخطيط المسارات، مخطط الارتفاع، استيراد وتصدير GPX',
      'مكتبة: مخيمات، مواقع تسلق، مواقع غوص، قمم، كهوف وأكواخ جبلية',
      'قاعدة بيانات التسلق: القطاعات، المسارات، تحويل الدرجات، سجل الصعود',
      'أندية جامعية: رحلات، تسجيل حضور، توثيق .edu، دوري الأندية',
    ],
    safety:
      'تنبيه السلامة: زر SOS وسيلة إشعار وليس ضماناً للإنقاذ. محتوى الإسعافات الأولية تعليمي؛ في الطوارئ اتصل برقم الطوارئ المحلي.',
    closing: 'خطة Explorer مجانية. Pro بـ ₺149 شهرياً، وPro Guide للمرشدين بـ ₺399 شهرياً.',
  },
  id: {
    title: 'Zirtan: hiking & kemah',
    subtitle: 'Teman, peta bahaya, SOS',
    short: 'Cari teman hiking, cek peta bahaya jalur, lalu berangkat dengan peta offline.',
    keywords: 'hiking,gunung,kemah,panjat tebing,gps,peta offline,sos,p3k,jalur,pendakian',
    promo: 'Baru: 12 panduan P3K offline dan nomor darurat sesuai negara. Paket Explorer gratis.',
    screens: [
      'Teman terverifikasi di dekatmu',
      'Bahaya jalur sebelum berangkat',
      'SOS: tekan dan tahan',
      'P3K tanpa sinyal',
      'Peta offline dan GPX',
      'Kegiatan klub jadi satu',
    ],
    intro:
      'Zirtan dibuat agar kamu naik gunung bersama dan lebih siap. Temukan pendaki terverifikasi di dekatmu, lihat kondisi jalur di peta bahaya komunitas, dan bawa perangkat keselamatan yang tetap bekerja tanpa sinyal.',
    features: [
      'ZMatch: teman terverifikasi di dekatmu dan perencanaan bersama',
      'Peta bahaya komunitas: batu jatuh, longsoran, banjir, satwa liar, jalur ditutup',
      'SOS tekan-tahan: nomor darurat sesuai negara, lokasi ke kontak, tim penyelamat terdekat',
      '12 panduan P3K offline: RJP, pendarahan, hipotermia, ketinggian, gigitan ular',
      'Peta offline, perencanaan rute, profil ketinggian, impor dan ekspor GPX',
      'Pustaka: area kemah, tebing panjat, titik selam, puncak, gua, dan pondok',
      'Basis data panjat tebing: sektor, jalur, konversi grade, logbook',
      'Klub kampus: kegiatan, RSVP, verifikasi .edu, liga klub',
    ],
    safety:
      'Catatan keselamatan: SOS adalah alat pemberitahuan, bukan jaminan penyelamatan. Materi P3K bersifat edukatif; saat darurat hubungi nomor darurat setempat.',
    closing: 'Paket Explorer gratis. Pro ₺149/bulan, Pro Guide ₺399/bulan untuk pemandu.',
  },
  th: {
    title: 'Zirtan: เดินป่าและแคมป์',
    subtitle: 'เพื่อนร่วมทาง แผนที่ SOS',
    short: 'หาเพื่อนเดินป่า ดูแผนที่จุดอันตราย แล้วออกเดินด้วยแผนที่ออฟไลน์และ SOS',
    keywords: 'เดินป่า,ภูเขา,แคมป์ปิ้ง,ปีนผา,gps,แผนที่ออฟไลน์,sos,ปฐมพยาบาล,เส้นทาง',
    promo: 'ใหม่: คู่มือปฐมพยาบาลออฟไลน์ 12 ชุด และเบอร์ฉุกเฉินตามประเทศ แผน Explorer ใช้ฟรี',
    screens: [
      'เพื่อนร่วมทางที่ยืนยันตัวตนใกล้คุณ',
      'ดูจุดอันตรายก่อนออกเดิน',
      'SOS: กดค้างไว้',
      'ปฐมพยาบาลแม้ไม่มีสัญญาณ',
      'แผนที่ออฟไลน์และ GPX',
      'ทริปของชมรมในที่เดียว',
    ],
    intro:
      'Zirtan สร้างมาเพื่อให้คุณออกเดินไปด้วยกันและเตรียมตัวดีกว่าเดิม หาเพื่อนร่วมทางที่ยืนยันตัวตนใกล้คุณ ดูแผนที่จุดอันตรายจากชุมชนว่ามีอะไรรออยู่บนเส้นทาง และพกเครื่องมือความปลอดภัยที่ยังทำงานได้แม้ไม่มีสัญญาณ',
    features: [
      'ZMatch: จับคู่กับเพื่อนร่วมทางที่ยืนยันตัวตนใกล้คุณ และวางแผนไปด้วยกัน',
      'แผนที่จุดอันตรายจากชุมชน: หินถล่ม หิมะถล่ม น้ำหลาก สัตว์ป่า เส้นทางปิด',
      'SOS กดค้าง: เบอร์ฉุกเฉินตามประเทศ ส่งพิกัดให้ผู้ติดต่อ หน่วยกู้ภัยที่ใกล้ที่สุด',
      'คู่มือปฐมพยาบาลออฟไลน์ 12 ชุด: CPR เลือดออก ภาวะตัวเย็น โรคแพ้ความสูง งูกัด',
      'แผนที่ออฟไลน์ วางแผนเส้นทาง โปรไฟล์ความสูง นำเข้า–ส่งออก GPX',
      'คลังข้อมูล: จุดกางเต็นท์ ผาปีน จุดดำน้ำ ยอดเขา ถ้ำ และที่พักบนภูเขา',
      'ฐานข้อมูลปีนผา: เซกเตอร์ เส้นทาง แปลงเกรด สมุดบันทึก',
      'ชมรมมหาวิทยาลัย: ทริป ลงชื่อเข้าร่วม ยืนยัน .edu ลีกชมรม',
    ],
    safety:
      'ข้อควรทราบด้านความปลอดภัย: SOS เป็นเครื่องมือแจ้งเตือน ไม่ใช่การรับประกันการช่วยเหลือ เนื้อหาปฐมพยาบาลมีไว้เพื่อการเรียนรู้ กรณีฉุกเฉินโปรดโทรเบอร์ฉุกเฉินในพื้นที่',
    closing: 'แผน Explorer ใช้ฟรี Pro ₺149/เดือน และ Pro Guide สำหรับไกด์ ₺399/เดือน',
  },
};
