import {
  Activity,
  ArrowLeft,
  AtSign,
  ArrowUp,
  ArrowRight,
  Award,
  BadgeCheck,
  Bell,
  BellRing,
  Bike,
  Bookmark,
  Calendar,
  Camera,
  Check,
  CheckCheck,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleAlert,
  CircleCheck,
  CircleX,
  Clock,
  CloudSun,
  Compass,
  Droplets,
  Ellipsis,
  Eye,
  EyeOff,
  Flag,
  Flame,
  Footprints,
  Gauge,
  Globe,
  Handshake,
  Heart,
  HeartHandshake,
  Hourglass,
  House,
  Image as ImageIcon,
  ImagePlus,
  Inbox,
  Info,
  Languages,
  LocateFixed,
  Lock,
  LogOut,
  Mail,
  Map as MapIcon,
  MapPin,
  MessageCircle,
  Moon,
  Mountain,
  MountainSnow,
  Navigation,
  Pencil,
  Plus,
  RefreshCw,
  Route,
  Ruler,
  Search,
  Send,
  Settings,
  Share2,
  ShieldCheck,
  SlidersHorizontal,
  Snowflake,
  Sparkles,
  Star,
  Sun,
  Sunrise,
  Tent,
  Thermometer,
  Timer,
  Trash,
  Trees,
  TrendingUp,
  TriangleAlert,
  Trophy,
  User,
  UserCheck,
  UserPlus,
  Users,
  WifiOff,
  Wind,
  X,
  Zap,
  type LucideIcon,
} from 'lucide-react-native';
import React from 'react';

import { useTheme } from '@/core/theme';

const registry = {
  activity: Activity,
  'arrow-left': ArrowLeft,
  'at-sign': AtSign,
  'arrow-up': ArrowUp,
  'arrow-right': ArrowRight,
  award: Award,
  'badge-check': BadgeCheck,
  bell: Bell,
  'bell-ring': BellRing,
  bike: Bike,
  bookmark: Bookmark,
  calendar: Calendar,
  camera: Camera,
  check: Check,
  'check-check': CheckCheck,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'circle-alert': CircleAlert,
  'circle-check': CircleCheck,
  'circle-x': CircleX,
  clock: Clock,
  'cloud-sun': CloudSun,
  compass: Compass,
  droplets: Droplets,
  ellipsis: Ellipsis,
  eye: Eye,
  'eye-off': EyeOff,
  flag: Flag,
  flame: Flame,
  footprints: Footprints,
  gauge: Gauge,
  globe: Globe,
  handshake: Handshake,
  heart: Heart,
  'heart-handshake': HeartHandshake,
  hourglass: Hourglass,
  house: House,
  image: ImageIcon,
  'image-plus': ImagePlus,
  inbox: Inbox,
  info: Info,
  languages: Languages,
  'locate-fixed': LocateFixed,
  lock: Lock,
  'log-out': LogOut,
  mail: Mail,
  map: MapIcon,
  'map-pin': MapPin,
  'message-circle': MessageCircle,
  moon: Moon,
  mountain: Mountain,
  'mountain-snow': MountainSnow,
  navigation: Navigation,
  pencil: Pencil,
  plus: Plus,
  'refresh-cw': RefreshCw,
  route: Route,
  ruler: Ruler,
  search: Search,
  send: Send,
  settings: Settings,
  share: Share2,
  'shield-check': ShieldCheck,
  sliders: SlidersHorizontal,
  snowflake: Snowflake,
  sparkles: Sparkles,
  star: Star,
  sun: Sun,
  sunrise: Sunrise,
  tent: Tent,
  thermometer: Thermometer,
  timer: Timer,
  trash: Trash,
  trees: Trees,
  'trending-up': TrendingUp,
  'triangle-alert': TriangleAlert,
  trophy: Trophy,
  user: User,
  'user-check': UserCheck,
  'user-plus': UserPlus,
  users: Users,
  'wifi-off': WifiOff,
  wind: Wind,
  x: X,
  zap: Zap,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof registry;

export interface IconProps {
  name: IconName;
  size?: number;
  color?: string;
  strokeWidth?: number;
  /** Dolgu rengi; kalp gibi ikonlarda "aktif" durum için */
  fill?: string;
}

export function Icon({ name, size = 20, color, strokeWidth = 2, fill = 'none' }: IconProps) {
  const { colors } = useTheme();
  const Component = registry[name];
  return (
    <Component size={size} color={color ?? colors.text} strokeWidth={strokeWidth} fill={fill} />
  );
}
